package com.mysql.repository;

import com.mysql.converter.jdbc.insert.InsertJdbcConverter;
import com.mysql.config.DataSource;
import com.mysql.entity.IdEntity;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public abstract class IntegerGenericRepository<E extends IdEntity> extends GenericRepository<E, Integer> {

    public IntegerGenericRepository(String tableName, String fieldId, DataSource dataSource, InsertJdbcConverter insertJdbcConverter) {
        super(tableName, fieldId, dataSource, insertJdbcConverter);
    }

    @Override
    protected int getAutoGeneratedKeys() {
        return Statement.RETURN_GENERATED_KEYS;
    }

    @Override
    protected void populateId(Statement statement, E entity) {
        ResultSet resultSet = null;
        try {
            resultSet = statement.getGeneratedKeys();
            resultSet.next();
            int id = resultSet.getInt(1);
            entity.setId(id);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } finally {
            close(resultSet);
        }
    }
}
